#! /bin/sh
##########################################################
#  |  __ \ \    / /  __ \| |        /\   |  _ \ / ____|  #
#  | |  | \ \  / /| |__) | |       /  \  | |_) | (___    #
#  | |  | |\ \/ / |  _  /| |      / /\ \ |  _ < \___ \   #
#  | |__| | \  /  | | \ \| |____ / ____ \| |_) |____) |  #
#  |_____/   \/   |_|  \_\______/_/    \_\____/|_____/   #
##########################################################
# CONFIGURATON - bspwmrc                                 #               
##########################################################
# SUMMARY      - init file for bspwm                     #      
##########################################################
# VERSION      - 1.2.0                                   # 
##########################################################
# DATE         - 06/30/22                                #      
##########################################################
# https://github.com/dvrlabs/bspwm-workspace             #                
##########################################################

#Start hot key daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

##########################################################
# Monitors/Workspaces                    left to right   # 
##########################################################
bspc monitor DVI-D-0 -d       1  2  3   
bspc monitor HDMI-A-0 -d      4  5  6 
bspc monitor DisplayPort-1 -d 7  8  9


##########################################################
# bspwm configuration options                            # 
##########################################################
bspc config border_width         5
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   false 
bspc config gapless_monocle      false 
bspc config focused_border_color \#3daee9
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner


##########################################################
# Rules for specific applications                        # 
##########################################################
bspc rule -a ulauncher state=floating follow=off 
bspc rule -a ulauncher-toggle state=floating follow=off 
bspc rule -a expandedViewDriver.py state=floating follow=off


##########################################################
# Autostart                                              # 
##########################################################
autorandr bspwm &
sh -c 'sleep 2; picom --experimental-backends -b  &'
sh -c 'sleep 2; exec nitrogen --restore &'
sh -c 'sleep 2; ~/.config/polybar/launch.sh &'
gnome-screensaver &
ulauncher --hide-window &
xsetroot -cursor_name left_ptr &



